from typing import Protocol


class SIDBackend(Protocol):
    def reset(self): ...
    def set_model(self, model: str): ...
    def write(self, register: int, value: int): ...
    def render(self, frames: int) -> bytes: ...
